### ISSUE TITLE
Please merge knyar / nginx-lua-prometheus for new feat.

### ISSUE THREAD

**Issue by yangxikun** [api7/lua-resty-prometheus#4]
I add a feat https://github.com/knyar/nginx-lua-prometheus/pull/114 to knyar / nginx-lua-prometheus.
Can lua-resty-prometheus merge it?

**Comment by yangxikun** [comment]
Also the origin repo had some bug fix need to be merged. Such as I encountered this bug: https://github.com/knyar/nginx-lua-prometheus/pull/106.

**Comment by yangxikun** [comment]
@spacewander @membphis Cloud you please review this issue?

**Comment by membphis** [comment]
welcome to submit a new PR to this project

**Comment by yangxikun** [comment]
Please make a release on https://luarocks.org/modules/membphis/lua-resty-prometheus

@membphis

**Comment by spacewander** [comment]
As this project is the same with knyar/nginx-lua-prometheus, why don't we use https://luarocks.org/modules/knyar/nginx-lua-prometheus directly?

**Comment by yangxikun** [comment]
Please make a release on https://luarocks.org/modules/membphis/lua-resty-prometheus

@membphis

**Comment by membphis** [comment]
@yangxikun you can submit a PR, then I will release a new version ^_^

**Comment by membphis** [comment]
> @yangxikun you can submit a PR, then I will release a new version ^_^

ignore what I said.



> As this project is the same with knyar/nginx-lua-prometheus, why don't we use https://luarocks.org/modules/knyar/nginx-lua-prometheus directly?

we can use this library directly now.

**Comment by membphis** [comment]
created a new issue: https://github.com/apache/apisix/issues/3238

we can close this issue now
